db:
  image: postgres
  container_name: dnd-app-database
  volumes:
    - ./tmp/db:/var/lib/postgresql/data
web:
  build: .
  command: bundle exec rails s -p 3000 -b "0.0.0.0"
  container_name: dnd-app
  volumes:
    - .:/myapp
  ports:
    - "3000:3000"
  links:
    - db